name: Daily News Update

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write  # This ensures the token has write access

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run news_locations.py
        run: python news_locations.py
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Run news_location_cleaning.py
        run: python news_location_cleaning.py

      - name: Run summarizer.py
        run: python summarizer.py
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Daily news update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
